FROM python:3.9-slim

WORKDIR /Neuronal-Network

COPY . .

RUN python -m venv venv && \
    . venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Define the command to start the application
CMD ["python", "prueba/a.py"]
