FROM python:3.9-slim

WORKDIR /Neuronal-Network

COPY . .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

EXPOSE 5000
# Define the command to start the application
CMD ["python", "prueba/a.py"]
